GET http://localhost:3020/api/users/get-user/6271586309154c55aece472e HTTP/1.1
###
POST http://localhost:3020/api/users/sign-in HTTP/1.1
content-type: application/json

{
	"username": "user 1 username"
}

###
###
GET http://localhost:3020/api/users/get-users HTTP/1.1
###
DELETE http://localhost:3020/api/users/all-users HTTP/1.1
###
GET http://localhost:3020/api/messages HTTP/1.1
###
DELETE http://localhost:3020/api/messages/delete-all HTTP/1.1
###
GET http://localhost:3020/api/users/get-users-in-chat HTTP/1.1
###
DELETE http://localhost:3020/api/users/all-users-in-chat HTTP/1.1